In [5]:
import pandas as pd
import os
import re

In [6]:
df = pd.read_csv("/home/nmh/ds/project/data_cleaning_homedy/homedy/homedy_concat.csv")
df.info()
print(df.columns.tolist())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2912 entries, 0 to 2911
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   2912 non-null   object
 1   Price                   2912 non-null   object
 2   Area                    2912 non-null   object
 3   Address                 2912 non-null   object
 4   Gen_descrip             2912 non-null   object
 5   Loại hình               2909 non-null   object
 6   Số phòng ngủ            1033 non-null   float64
 7   Tình trạng pháp lý      1404 non-null   object
 8   Ngày đăng               2912 non-null   object
 9   Ngày hết hạn            2912 non-null   object
 10  Loại tin                2912 non-null   object
 11  ID tin                  2912 non-null   int64
 12  Bình nóng lạnh          859 non-null    float64
 13  Máy hút mùi             777 non-null    float64
 14  Tủ bếp                  802 non-null    float64
 15  Bàn ăn                  738 non-null    float64
 16  Kệ TV                   706 non-null    float64
 17  Tủ trang trí            689 non-null    float64
 18  Giường ngủ              694 non-null    float64
 19  Bàn phấn                656 non-null    float64
 20  Tủ quần áo              718 non-null    float64
 21  Bồn tắm                 789 non-null    float64
 22  Vòi hoa sen             869 non-null    float64
 23  Bồn cầu                 870 non-null    float64
 24  Bồn rửa mặt             869 non-null    float64
 25  Bàn ghế P.khách         673 non-null    float64
 26  Hướng nhà               712 non-null    object
 27  Số tầng                 201 non-null    float64
 28  Mặt tiền                63 non-null     object
 29  Nội thất                157 non-null    object
 30  Hướng ban công          85 non-null     object
 31  Căn góc                 144 non-null    object
 32  Đường vào               50 non-null     object
 33  Chiều sâu               9 non-null      object
 34  Đã bao gồm thuế?        6 non-null      object
 35  Chính chủ hay không?    6 non-null      object
 36  Sofa phòng khách        7 non-null      float64
 37  Bàn trà                 7 non-null      float64
 38  Đệm                     7 non-null      float64
 39  Trần thả                7 non-null      float64
 40  Tổng diện tích sử dụng  1 non-null      object
dtypes: float64(20), int64(1), object(20)
memory usage: 932.9+ KB
['Title', 'Price', 'Area', 'Address', 'Gen_descrip', 'Loại hình', 'Số phòng ngủ', 'Tình trạng pháp lý', 'Ngày đăng', 'Ngày hết hạn', 'Loại tin', 'ID tin', 'Bình nóng lạnh', 'Máy hút mùi', 'Tủ bếp', 'Bàn ăn', 'Kệ TV', 'Tủ trang trí', 'Giường ngủ', 'Bàn phấn', 'Tủ quần áo', 'Bồn tắm', 'Vòi hoa sen', 'Bồn cầu', 'Bồn rửa mặt', 'Bàn ghế P.khách', 'Hướng nhà', 'Số tầng', 'Mặt tiền', 'Nội thất', 'Hướng ban công', 'Căn góc', 'Đường vào', 'Chiều sâu', 'Đã bao gồm thuế?', 'Chính chủ hay không?', 'Sofa phòng khách', 'Bàn trà', 'Đệm', 'Trần thả', 'Tổng diện tích sử dụng']

,Title,Price,Area,Address,Gen_descrip,Loại hình,Số phòng ngủ,Tình trạng pháp lý,Ngày đăng,Ngày hết hạn,...,Căn góc,Đường vào,Chiều sâu,Đã bao gồm thuế?,Chính chủ hay không?,Sofa phòng khách,Bàn trà,Đệm,Trần thả,Tổng diện tích sử dụng
0,"\nBán tòa vp phố trung yên, kđt yên hòa, sát p...",\n31\nTỷ,\n110\nm2\n,"['Hà Nội', 'Quận Cầu Giấy', 'Mua bán Nhà riêng...",\n\nKĐT YÊN HÒA - PHÂN LÔ - 3 OTO TRÁNH - VỈA ...,Nhà riêng,7.0,Sổ đỏ,11/10/2023,08/11/2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,\nBán nhà Mỹ Đình - Nam Từ Liêm. Mặt ngõ ô tô ...,"\n5,95\nTỷ",\n31\nm2\n,"['Hà Nội', 'Quận Nam Từ Liêm', 'Mua bán Nhà mặ...",\nGia chủ cần bán gấp căn nhà ở mặt ngõ đường ...,Nhà mặt phố,NaN,Sổ hồng,11/10/2023,25/10/2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"\nBán Toà VP phố Nghĩa Đô- 90m2x9 Tầng, Ô TÔ t...",\n28\nTỷ,\n90\nm2\n,"['Hà Nội', 'Quận Cầu Giấy', 'Mua bán Nhà riêng...",\nPHỐ VIP NGHĨA ĐÔ- TOÀ NHÀ XÂY MỚI-KINH DOANH...,Nhà riêng,NaN,Sổ đỏ,11/10/2023,08/11/2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,\nBán tòa nhà Văn Phòng 9 tầng mặt phố Vũ Tô...,\n80\nTỷ,\n145\nm2\n,"['Hà Nội', 'Quận Thanh Xuân', 'Mua bán Nhà mặt...",\nCần bán gấp Tòa Nhà Văn Phòng VIP 9 tầng xây...,Nhà mặt phố,NaN,Sổ đỏ,11/10/2023,08/11/2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,\nChính chủ cần bán nhanh căn góc Duplex PentS...,"\n4,6\nTỷ",\n76\nm2\n,['Mua bán Căn hộ chung cư PentStudio'],\nGia đình cần bán gấp căn hộ PentStudio diện ...,Căn hộ,NaN,Sổ hồng,11/10/2023,08/11/2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.dtypes

Title                      object
Price                      object
Area                       object
Address                    object
Gen_descrip                object
Loại hình                  object
Số phòng ngủ              float64
Tình trạng pháp lý         object
Ngày đăng                  object
Ngày hết hạn               object
Loại tin                   object
ID tin                      int64
Bình nóng lạnh            float64
Máy hút mùi               float64
Tủ bếp                    float64
Bàn ăn                    float64
Kệ TV                     float64
Tủ trang trí              float64
Giường ngủ                float64
Bàn phấn                  float64
Tủ quần áo                float64
Bồn tắm                   float64
Vòi hoa sen               float64
Bồn cầu                   float64
Bồn rửa mặt               float64
Bàn ghế P.khách           float64
Hướng nhà                  object
Số tầng                   float64
Mặt tiền                   object
Nội thất                   object
Hướng ban công             object
Căn góc                    object
Đường vào                  object
Chiều sâu                  object
Đã bao gồm thuế?           object
Chính chủ hay không?       object
Sofa phòng khách          float64
Bàn trà                   float64
Đệm                       float64
Trần thả                  float64
Tổng diện tích sử dụng     object
dtype: object

In [8]:
unique_values = df['Mặt tiền'].unique()
print(unique_values)

[nan '5m' '12m' '45m' '3,6m' '3m' '3,5m' '3,8m' '4m' '58m' '75m' '5,7m'
 '8,3m' '16m' '10m' '6m' '5,5m' '9,5m' '84m' '83m' '6,2m' '7,5m' '8m' '9m'
 '7m' '4,5m']

In [9]:
def extract_address_components(address):
    if not isinstance(address, str):
        return ["", "", ""]
    address_parts = re.findall(r"'([^']*)'", address)

    district, ward, street = "", "", ""

    # Extract district
    if len(address_parts) > 1:
        if 'Quận' in address_parts[1]:
            district = address_parts[1].split('Quận ')[-1]
        if 'Huyện' in address_parts[1]:
            district = address_parts[1].split('Huyện ')[-1]

    # Extract ward or street
    if len(address_parts) > 2:
        address_component = address_parts[2]
        if 'Quận' in address_component:
            district = address_component.split('Quận ')[-1]
        if 'Huyện' in address_component:
            district = address_component.split('Huyện ')[-1]
        if 'Phường' in address_component:
            ward = address_component.split('Phường ')[-1]
        if 'Xã' in address_component:
            ward = address_component.split('Xã ')[-1]
        if 'Đường' in address_component:
            street = address_component.split('Đường ')[-1]
        if 'Phố' in address_component:
            street = address_component.split('Phố ')[-1]

    return [street, ward, district]

In [10]:
address = extract_address_components("['Hà Nội', 'Mua bán Nhà riêng tại Quận Hoàng Mai']")
print(address)

['', '', 'Hoàng Mai']

In [11]:
def calculate_average(range_str):
    parts = range_str.strip().split('-')
    # for part in parts:
        # print(part)
    if len(parts) == 2:
        try:
            lower_bound = float(parts[0].strip().replace(',', '.'))
            upper_bound = float(parts[1].strip().replace(',', '.'))
            return (lower_bound + upper_bound) / 2
        except ValueError:
            return None
    else:
        try:
            # print(float(parts[0]))
            return float(parts[0].strip().replace(',', '.'))
        except ValueError:
            return None

In [12]:
def convert_area(area_str):
    if not isinstance(area_str, str):
        return None

    # Cleaning and converting area
    area = calculate_average(area_str.replace('m2', '').replace(' ', ''))

    return area

In [13]:
area_str = "35 - 55m2"

print(convert_area(area_str))

45.0

In [14]:
def convert_price(price_str, area_str):
    if not isinstance(price_str, str) and not isinstance(area_str, str):
        return None
    price_str = price_str.lower().replace(',', '.').strip()
    # print(price_str)
    area = convert_area(area_str)
    # print(area)

    price = None
    
    if '/tháng' in price_str:
        return None
    if 'tỷ' in price_str:
        new_price_str = price_str.replace('tỷ VNĐ', '').replace('tỷ', '')
        # print("start calculate for price")
        price = calculate_average(new_price_str)
        # print(price)
        if price is not None:
            return price * 1000  # Convert from 'tỷ' to 'triệu'
    elif 'triệu' in price_str:
        price_str = price_str.replace(' triệu VNĐ', '').replace(' triệu', '')
        price = calculate_average(price_str)
        return price
    elif '/m2' in price_str:
        price_str = price_str.replace('/m2', '')
        price_per_m2 = calculate_average(price_str)
        if price_per_m2 is not None and area is not None:
            return price_per_m2 * area

    if price is None or area is None:
        return None

    return price

In [15]:
price = "2,9Tỷ "
area = "33m2"
print(convert_price(price, area))

2900.0

In [16]:
def clean_direction(direction_str):
    direction_map = {
        'đông': 'E', 'tây': 'W', 'nam': 'S', 'bắc': 'N',
        'tây-bắc': 'WN', 'tây-nam': 'WS', 'đông-bắc': 'EN', 'đông-nam': 'ES'
    }
    direction_str = direction_str.lower().strip() if isinstance(direction_str, str) else direction_str
    return direction_map.get(direction_str, "")

In [17]:
def convert_to_numeric(value):
    if isinstance(value, str):
        value = value.replace('m', '').replace(',', '.')
        try:
            return float(value)
        except ValueError:
            return None
    return value

In [18]:
df['id'] = df['ID tin']

df[['street', 'ward', 'district']] = df['Address'].fillna("").apply(lambda x: pd.Series(extract_address_components(x)))
df['city'] = 'Hà Nội'

df['area'] = df['Area'].apply(convert_area)

df['price'] = df.apply(lambda row: convert_price(row['Price'], row['Area']), axis=1)

if 'Hướng nhà' in df.columns and df['Hướng nhà'].notnull().any():
    df['house_direction'] = df['Hướng nhà'].apply(clean_direction)
else:
    df['house_direction'] = None

if 'Số phòng ngủ' in df.columns:
    df['bedroom'] = pd.to_numeric(df['Số phòng ngủ'], errors='coerce')
else:
    df['bedroom'] = None

if 'Bồn cầu' in df.columns:
    df['toilet'] = pd.to_numeric(df['Bồn cầu'], errors='coerce')
else:
    df['toilet'] = None

if 'Số tầng' in df.columns:
    df['floors'] = pd.to_numeric(df['Số tầng'], errors='coerce')
else:
    df['floors'] = None

if 'Ngày đăng' in df.columns:
    df['upload_date'] = df['Ngày đăng']
else:
    df['date'] = None

if 'Nội thất' in df.columns:
    df['furniture'] = df['Nội thất']
else:
    df['furniture'] = None

if 'Tình trạng pháp lý' in df.columns:
    df['legits'] = df['Tình trạng pháp lý']
else:
    df['legits'] = None

if 'Mặt tiền' in df.columns:
    df['facade'] = df['Mặt tiền'].apply(convert_to_numeric)
else:
    df['facade'] = None

if 'Đường vào' in df.columns:
    df['entrance'] = df['Đường vào'].apply(convert_to_numeric)
else:
    df['entrance'] = None   

df = df[df['price'].notnull()]

final_columns = ['id', 'city', 'district', 'ward', 'street', 'area', 'price', 'house_direction', 
                         'bedroom', 'toilet', 'floors', 'legits','upload_date', 'furniture', 
                         'facade', 'entrance']
df_final = df[final_columns]

In [19]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2283 entries, 0 to 2911
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2283 non-null   int64
 1   city             2283 non-null   object
 2   district         2283 non-null   object
 3   ward             2283 non-null   object
 4   street           2283 non-null   object
 5   area             2224 non-null   float64
 6   price            2283 non-null   float64
 7   house_direction  2283 non-null   object
 8   bedroom          837 non-null    float64
 9   toilet           642 non-null    float64
 10  floors           128 non-null    float64
 11  legits           1063 non-null   object
 12  upload_date      2283 non-null   object
 13  furniture        78 non-null     object
 14  facade           45 non-null     float64
 15  entrance         34 non-null     float64
dtypes: float64(7), int64(1), object(8)
memory usage: 303.2+ KB

In [20]:
# combined_df = pd.concat(all_dfs, ignore_index=True)
df_final.to_csv('cleaned_data_test.csv', index=False)

In [21]:
for column in df_final.columns:
    print(f"Column: {column}")
    print(df_final[column].head())  
    print("\n")

Column: id
0    2567389
1    2567352
2    2567348
3    2567310
4    2567242
Name: id, dtype: int64


Column: city
0    Hà Nội
1    Hà Nội
2    Hà Nội
3    Hà Nội
4    Hà Nội
Name: city, dtype: object


Column: district
0       Cầu Giấy
1    Nam Từ Liêm
2       Cầu Giấy
3     Thanh Xuân
4
Name: district, dtype: object


Column: ward
0
1
2
3
4
Name: ward, dtype: object


Column: street
0    Nam Trung Yên
1
2         Nghĩa Đô
3     Vũ Tông Phan
4
Name: street, dtype: object


Column: area
0    110.0
1     31.0
2     90.0
3    145.0
4     76.0
Name: area, dtype: float64


Column: price
0    31000.0
1     5950.0
2    28000.0
3    80000.0
4     4600.0
Name: price, dtype: float64


Column: house_direction
0
1
2
3
4    ES
Name: house_direction, dtype: object


Column: bedroom
0    7.0
1    NaN
2    NaN
3    NaN
4    NaN
Name: bedroom, dtype: float64


Column: toilet
0    NaN
1    1.0
2    1.0
3    NaN
4    1.0
Name: toilet, dtype: float64


Column: floors
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: floors, dtype: float64


Column: legits
0      Sổ đỏ
1    Sổ hồng
2      Sổ đỏ
3      Sổ đỏ
4    Sổ hồng
Name: legits, dtype: object


Column: upload_date
0     11/10/2023
1     11/10/2023
2     11/10/2023
3     11/10/2023
4     11/10/2023
Name: upload_date, dtype: object


Column: furniture
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: furniture, dtype: object


Column: facade
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: facade, dtype: float64


Column: entrance
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: entrance, dtype: float64

In [22]:
missing_percentages = df_final.isnull().mean() * 100

print("Percentage of Missing Values per Column:")
print(missing_percentages)

Percentage of Missing Values per Column:
id                  0.000000
city                0.000000
district            0.000000
ward                0.000000
street              0.000000
area                2.584319
price               0.000000
house_direction     0.000000
bedroom            63.337714
toilet             71.879106
floors             94.393342
legits             53.438458
upload_date         0.000000
furniture          96.583443
facade             98.028909
entrance           98.510731
dtype: float64